### ISSUE TITLE
NPE in client connection handling

### ISSUE THREAD

**Issue by MarkNSweep** [gameontext/gameon-mediator#64] opened 2016-10-14 09:50 UTC
Lots of these occurring in the mediator log

[10/13/16 14:47:22:176 UTC] 0001d2f6 net.wasdev.gameon.mediator                                   W : adc2dbc3 : Uncaught exception handling client-bound message
java.lang.NullPointerException
    at org.gameontext.mediator.MediatorNexus$SingleUserView.stillConnected(MediatorNexus.java:595)
    at org.gameontext.mediator.MediatorNexus$SingleUserView.sendToClients(MediatorNexus.java:586)
    at org.gameontext.mediator.room.WebSocketClientConnection$1.onMessage(WebSocketClientConnection.java:122)
    at org.gameontext.mediator.room.WebSocketClientConnection$1.onMessage(WebSocketClientConnection.java:112)
    at com.ibm.ws.wsoc.LinkRead.processWithWholeMessageHandler(LinkRead.java:645)
    at com.ibm.ws.wsoc.LinkRead.processRead(LinkRead.java:339)
    at com.ibm.ws.wsoc.WsocConnLink.processRead(WsocConnLink.java:895)
    at com.ibm.ws.wsoc.WsocReadCallback.completeLogic(WsocReadCallback.java:51)
    at com.ibm.ws.wsoc.WsocReadCallback.complete(WsocReadCallback.java:37)
    at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1777)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:929)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1018)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:785)

**Comment by ebullient** [comment] 2016-11-08 21:02
Duplicate of #48

**Closed as completed by ebullient** 2016-11-08 21:02 UTC
Labels: bug
